export const branches = ["All Branches", "Guntur", "Vijayawada"] as const;
export type Branch = (typeof branches)[number];
export const leads = [
  {
    id: "LD-24091",
    name: "Ananya Rao",
    phone: "+91 9XXXX 11001",
    email: "ananya.rao@example.test",
    course: "Data Science",
    branch: "Guntur",
    source: "Organic Social Media",
    channel: "WhatsApp",
    entryMethod: "Staff entered",
    intakeStatus: "New",
    owner: "Counsellor A (GNT)",
    stage: "Demo Scheduled",
    followUp: "Today, 4:30 PM",
    age: "2d",
    priority: "Hot",
    score: 92,
  },
  {
    id: "LD-24088",
    name: "Karthik Reddy",
    phone: "+91 9XXXX 11002",
    email: "karthik.reddy@example.test",
    course: "Java Full Stack",
    branch: "Vijayawada",
    source: "Google Ads",
    owner: "Counsellor C (VIJ)",
    channel: "Phone call",
    entryMethod: "Google Ads form",
    intakeStatus: "New",
    stage: "Fee Discussion / Payment Awaited",
    followUp: "Today, 5:15 PM",
    age: "4d",
    priority: "Hot",
    score: 88,
  },
  {
    id: "LD-24076",
    name: "Meghana Varma",
    phone: "+91 9XXXX 11003",
    email: "meghana.varma@example.test",
    course: "Power BI",
    branch: "Guntur",
    source: "Walk-in",
    owner: "Counsellor A (GNT)",
    channel: "In person",
    entryMethod: "Walk-in desk",
    intakeStatus: "Incomplete",
    stage: "Counselling",
    followUp: "Overdue 1d",
    age: "6d",
    priority: "Warm",
    score: 73,
  },
  {
    id: "LD-24061",
    name: "Sai Teja",
    phone: "+91 9XXXX 11004",
    email: "sai.teja@example.test",
    course: "AWS with DevOps",
    branch: "Vijayawada",
    source: "Referral",
    channel: "Phone call",
    entryMethod: "Staff entered",
    intakeStatus: "Duplicate Review",
    owner: "Front Office D (VIJ)",
    stage: "Demo Attended",
    followUp: "Tomorrow, 11 AM",
    age: "9d",
    priority: "Warm",
    score: 68,
  },
  {
    id: "LD-24049",
    name: "Harini Chowdary",
    phone: "+91 9XXXX 11005",
    email: "harini.c@example.test",
    course: "Digital Marketing",
    branch: "Guntur",
    source: "Website",
    channel: "Web form",
    entryMethod: "Website",
    intakeStatus: "New",
    owner: "Front Office B (GNT)",
    stage: "New Enquiry",
    followUp: "Unscheduled",
    age: "1d",
    priority: "Waiting for Batch / Future Joining",
    score: 41,
  },
  {
    id: "LD-24037",
    name: "Vamsi Krishna",
    phone: "+91 9XXXX 11006",
    email: "vamsi.k@example.test",
    course: "Python Full Stack",
    branch: "Vijayawada",
    source: "College Data",
    channel: "Outbound call",
    entryMethod: "Bulk outreach import",
    intakeStatus: "Outreach Prospect",
    owner: "Counsellor C (VIJ)",
    stage: "Payment Pending Verification",
    followUp: "25 Sep, 10 AM",
    age: "12d",
    priority: "Hot",
    score: 85,
  },
];
export const navItems = [
  ["Dashboard", "/dashboard"],
  ["Leads", "/leads"],
  ["Pipeline", "/pipeline"],
  ["Demos", "/demos"],
  ["Admissions", "/admissions"],
  ["Batches", "/batches"],
  ["Students", "/students"],
  ["Payments", "/payments"],
  ["Invoices", "/invoices"],
  ["Collections", "/collections"],
  ["Refunds", "/refunds"],
  ["Tasks", "/tasks"],
  ["Communications", "/communications"],
  ["Reports", "/reports"],
  ["Placement & Alumni", "/placement-alumni"],
  ["AI Copilot", "/ai-copilot"],
  ["Course Master", "/course-master"],
] as const;
export const courses = [
  "Data Science",
  "Java Full Stack",
  "Python Full Stack",
  "AWS with DevOps",
  "Power BI",
  "Digital Marketing",
  "Graphic Design",
  "Video Editing",
];
