/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as AskNipunaRouteImport } from './routes/ask-nipuna'
import { Route as BranchManagerRouteImport } from './routes/branch-manager'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CounsellorRouteImport } from './routes/counsellor'
import { Route as CourseMasterRouteImport } from './routes/course-master'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemosRouteImport } from './routes/demos'
import { Route as DiscountApprovalRouteImport } from './routes/discount-approval'
import { Route as FeeQuoteRouteImport } from './routes/fee-quote'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfferMasterRouteImport } from './routes/offer-master'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PlacementAlumniRouteImport } from './routes/placement-alumni'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TargetMasterRouteImport } from './routes/target-master'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions.index'
import { Route as AdmissionsNewRouteImport } from './routes/admissions.new'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as PipelineValidationRouteImport } from './routes/pipeline.validation'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsPersonIdRouteImport } from './routes/students.$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AskNipunaRoute = AskNipunaRouteImport.update({
  id: '/ask-nipuna',
  path: '/ask-nipuna',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchManagerRoute = BranchManagerRouteImport.update({
  id: '/branch-manager',
  path: '/branch-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorRoute = CounsellorRouteImport.update({
  id: '/counsellor',
  path: '/counsellor',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseMasterRoute = CourseMasterRouteImport.update({
  id: '/course-master',
  path: '/course-master',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountApprovalRoute = DiscountApprovalRouteImport.update({
  id: '/discount-approval',
  path: '/discount-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeQuoteRoute = FeeQuoteRouteImport.update({
  id: '/fee-quote',
  path: '/fee-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferMasterRoute = OfferMasterRouteImport.update({
  id: '/offer-master',
  path: '/offer-master',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementAlumniRoute = PlacementAlumniRouteImport.update({
  id: '/placement-alumni',
  path: '/placement-alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetMasterRoute = TargetMasterRouteImport.update({
  id: '/target-master',
  path: '/target-master',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AdmissionsNewRoute = AdmissionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdmissionsRoute,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const PipelineValidationRoute = PipelineValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => PipelineRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsPersonIdRoute = StudentsPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => StudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/ai-copilot': typeof AiCopilotRoute
  '/ask-nipuna': typeof AskNipunaRoute
  '/branch-manager': typeof BranchManagerRoute
  '/collections': typeof CollectionsRoute
  '/communications': typeof CommunicationsRoute
  '/counsellor': typeof CounsellorRoute
  '/course-master': typeof CourseMasterRoute
  '/dashboard': typeof DashboardRoute
  '/demos': typeof DemosRoute
  '/discount-approval': typeof DiscountApprovalRoute
  '/fee-quote': typeof FeeQuoteRoute
  '/leads': typeof LeadsRouteWithChildren
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/offer-master': typeof OfferMasterRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/placement-alumni': typeof PlacementAlumniRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/target-master': typeof TargetMasterRoute
  '/tasks': typeof TasksRoute
  '/admissions/new': typeof AdmissionsNewRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/pipeline/validation': typeof PipelineValidationRoute
  '/students/$personId': typeof StudentsPersonIdRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/batches/': typeof BatchesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/ask-nipuna': typeof AskNipunaRoute
  '/branch-manager': typeof BranchManagerRoute
  '/collections': typeof CollectionsRoute
  '/communications': typeof CommunicationsRoute
  '/counsellor': typeof CounsellorRoute
  '/course-master': typeof CourseMasterRoute
  '/dashboard': typeof DashboardRoute
  '/demos': typeof DemosRoute
  '/discount-approval': typeof DiscountApprovalRoute
  '/fee-quote': typeof FeeQuoteRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/offer-master': typeof OfferMasterRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/placement-alumni': typeof PlacementAlumniRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/target-master': typeof TargetMasterRoute
  '/tasks': typeof TasksRoute
  '/admissions/new': typeof AdmissionsNewRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/pipeline/validation': typeof PipelineValidationRoute
  '/students/$personId': typeof StudentsPersonIdRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/batches': typeof BatchesIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/ai-copilot': typeof AiCopilotRoute
  '/ask-nipuna': typeof AskNipunaRoute
  '/branch-manager': typeof BranchManagerRoute
  '/collections': typeof CollectionsRoute
  '/communications': typeof CommunicationsRoute
  '/counsellor': typeof CounsellorRoute
  '/course-master': typeof CourseMasterRoute
  '/dashboard': typeof DashboardRoute
  '/demos': typeof DemosRoute
  '/discount-approval': typeof DiscountApprovalRoute
  '/fee-quote': typeof FeeQuoteRoute
  '/leads': typeof LeadsRouteWithChildren
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/offer-master': typeof OfferMasterRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/placement-alumni': typeof PlacementAlumniRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/target-master': typeof TargetMasterRoute
  '/tasks': typeof TasksRoute
  '/admissions/new': typeof AdmissionsNewRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/pipeline/validation': typeof PipelineValidationRoute
  '/students/$personId': typeof StudentsPersonIdRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/batches/': typeof BatchesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/admissions'
    | '/ai-copilot'
    | '/ask-nipuna'
    | '/branch-manager'
    | '/collections'
    | '/communications'
    | '/counsellor'
    | '/course-master'
    | '/dashboard'
    | '/demos'
    | '/discount-approval'
    | '/fee-quote'
    | '/leads'
    | '/more'
    | '/notifications'
    | '/offer-master'
    | '/payments'
    | '/pipeline'
    | '/placement-alumni'
    | '/refunds'
    | '/reports'
    | '/students'
    | '/target-master'
    | '/tasks'
    | '/admissions/new'
    | '/batches/$batchId'
    | '/invoices/$invoiceId'
    | '/leads/$leadId'
    | '/pipeline/validation'
    | '/students/$personId'
    | '/admissions/'
    | '/batches/'
    | '/invoices/'
    | '/leads/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/ai-copilot'
    | '/ask-nipuna'
    | '/branch-manager'
    | '/collections'
    | '/communications'
    | '/counsellor'
    | '/course-master'
    | '/dashboard'
    | '/demos'
    | '/discount-approval'
    | '/fee-quote'
    | '/more'
    | '/notifications'
    | '/offer-master'
    | '/payments'
    | '/pipeline'
    | '/placement-alumni'
    | '/refunds'
    | '/reports'
    | '/target-master'
    | '/tasks'
    | '/admissions/new'
    | '/batches/$batchId'
    | '/invoices/$invoiceId'
    | '/leads/$leadId'
    | '/pipeline/validation'
    | '/students/$personId'
    | '/admissions'
    | '/batches'
    | '/invoices'
    | '/leads'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/admissions'
    | '/ai-copilot'
    | '/ask-nipuna'
    | '/branch-manager'
    | '/collections'
    | '/communications'
    | '/counsellor'
    | '/course-master'
    | '/dashboard'
    | '/demos'
    | '/discount-approval'
    | '/fee-quote'
    | '/leads'
    | '/more'
    | '/notifications'
    | '/offer-master'
    | '/payments'
    | '/pipeline'
    | '/placement-alumni'
    | '/refunds'
    | '/reports'
    | '/students'
    | '/target-master'
    | '/tasks'
    | '/admissions/new'
    | '/batches/$batchId'
    | '/invoices/$invoiceId'
    | '/leads/$leadId'
    | '/pipeline/validation'
    | '/students/$personId'
    | '/admissions/'
    | '/batches/'
    | '/invoices/'
    | '/leads/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRoute
  AdmissionsRoute: typeof AdmissionsRouteWithChildren
  AiCopilotRoute: typeof AiCopilotRoute
  AskNipunaRoute: typeof AskNipunaRoute
  BranchManagerRoute: typeof BranchManagerRoute
  CollectionsRoute: typeof CollectionsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  CounsellorRoute: typeof CounsellorRoute
  CourseMasterRoute: typeof CourseMasterRoute
  DashboardRoute: typeof DashboardRoute
  DemosRoute: typeof DemosRoute
  DiscountApprovalRoute: typeof DiscountApprovalRoute
  FeeQuoteRoute: typeof FeeQuoteRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  OfferMasterRoute: typeof OfferMasterRoute
  PaymentsRoute: typeof PaymentsRoute
  PipelineRoute: typeof PipelineRouteWithChildren
  PlacementAlumniRoute: typeof PlacementAlumniRoute
  RefundsRoute: typeof RefundsRoute
  ReportsRoute: typeof ReportsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  TargetMasterRoute: typeof TargetMasterRoute
  TasksRoute: typeof TasksRoute
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-nipuna': {
      id: '/ask-nipuna'
      path: '/ask-nipuna'
      fullPath: '/ask-nipuna'
      preLoaderRoute: typeof AskNipunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-manager': {
      id: '/branch-manager'
      path: '/branch-manager'
      fullPath: '/branch-manager'
      preLoaderRoute: typeof BranchManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor': {
      id: '/counsellor'
      path: '/counsellor'
      fullPath: '/counsellor'
      preLoaderRoute: typeof CounsellorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-master': {
      id: '/course-master'
      path: '/course-master'
      fullPath: '/course-master'
      preLoaderRoute: typeof CourseMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-approval': {
      id: '/discount-approval'
      path: '/discount-approval'
      fullPath: '/discount-approval'
      preLoaderRoute: typeof DiscountApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-quote': {
      id: '/fee-quote'
      path: '/fee-quote'
      fullPath: '/fee-quote'
      preLoaderRoute: typeof FeeQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-master': {
      id: '/offer-master'
      path: '/offer-master'
      fullPath: '/offer-master'
      preLoaderRoute: typeof OfferMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-alumni': {
      id: '/placement-alumni'
      path: '/placement-alumni'
      fullPath: '/placement-alumni'
      preLoaderRoute: typeof PlacementAlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-master': {
      id: '/target-master'
      path: '/target-master'
      fullPath: '/target-master'
      preLoaderRoute: typeof TargetMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/admissions/new': {
      id: '/admissions/new'
      path: '/new'
      fullPath: '/admissions/new'
      preLoaderRoute: typeof AdmissionsNewRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/pipeline/validation': {
      id: '/pipeline/validation'
      path: '/validation'
      fullPath: '/pipeline/validation'
      preLoaderRoute: typeof PipelineValidationRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/$personId': {
      id: '/students/$personId'
      path: '/$personId'
      fullPath: '/students/$personId'
      preLoaderRoute: typeof StudentsPersonIdRouteImport
      parentRoute: typeof StudentsRoute
    }
  }
}

interface AdmissionsRouteChildren {
  AdmissionsNewRoute: typeof AdmissionsNewRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
}

const AdmissionsRouteChildren: AdmissionsRouteChildren = {
  AdmissionsNewRoute: AdmissionsNewRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
}

const AdmissionsRouteWithChildren = AdmissionsRoute._addFileChildren(
  AdmissionsRouteChildren,
)

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface PipelineRouteChildren {
  PipelineValidationRoute: typeof PipelineValidationRoute
}

const PipelineRouteChildren: PipelineRouteChildren = {
  PipelineValidationRoute: PipelineValidationRoute,
}

const PipelineRouteWithChildren = PipelineRoute._addFileChildren(
  PipelineRouteChildren,
)

interface StudentsRouteChildren {
  StudentsPersonIdRoute: typeof StudentsPersonIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsPersonIdRoute: StudentsPersonIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRoute,
  AdmissionsRoute: AdmissionsRouteWithChildren,
  AiCopilotRoute: AiCopilotRoute,
  AskNipunaRoute: AskNipunaRoute,
  BranchManagerRoute: BranchManagerRoute,
  CollectionsRoute: CollectionsRoute,
  CommunicationsRoute: CommunicationsRoute,
  CounsellorRoute: CounsellorRoute,
  CourseMasterRoute: CourseMasterRoute,
  DashboardRoute: DashboardRoute,
  DemosRoute: DemosRoute,
  DiscountApprovalRoute: DiscountApprovalRoute,
  FeeQuoteRoute: FeeQuoteRoute,
  LeadsRoute: LeadsRouteWithChildren,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  OfferMasterRoute: OfferMasterRoute,
  PaymentsRoute: PaymentsRoute,
  PipelineRoute: PipelineRouteWithChildren,
  PlacementAlumniRoute: PlacementAlumniRoute,
  RefundsRoute: RefundsRoute,
  ReportsRoute: ReportsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  TargetMasterRoute: TargetMasterRoute,
  TasksRoute: TasksRoute,
  BatchesBatchIdRoute: BatchesBatchIdRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
