"""Postgres enum types (created by db/*.sql) and their allowed values, used for validation."""
from sqlalchemy.dialects.postgresql import ENUM


def _pg_enum(name: str, values: tuple[str, ...]) -> ENUM:
    return ENUM(*values, name=name, create_type=False)


COURSE_STATUSES = ("Active", "Inactive", "Archived")
OFFER_STATUSES = ("Draft", "Configured", "Active", "Inactive", "Expired")
OFFER_BENEFIT_TYPES = ("Discount Amount", "Discount Percent", "Complimentary Course")
LEAD_STAGES = (
    "New Enquiry", "Counselling", "Demo Scheduled", "Demo Attended",
    "Fee Discussion / Payment Awaited", "Payment Pending Verification", "Admitted", "Lost - closed",
)
INTAKE_STATUSES = ("New", "Incomplete", "Duplicate Review", "Outreach Prospect", "Invalid-Spam", "Test")
LEAD_PRIORITIES = ("Hot", "Warm", "Cold", "Waiting for Batch / Future Joining")
ACTIVITY_TYPES = (
    "Call", "WhatsApp", "Email", "SMS", "Meeting", "Note", "Stage Change", "Assignment Change", "Follow-up Scheduled",
)
ACTIVITY_DIRECTIONS = ("Inbound", "Outbound")
LANGUAGES = ("English", "Telugu")
TASK_STATUSES = ("Open", "In Progress", "Waiting/Blocked", "Completed", "Cancelled")
TASK_SOURCES = ("Manual", "System")
NOTIFICATION_CATEGORIES = ("Action Required", "Escalation", "Information", "System Issue")
EXTERNAL_DELIVERY_STATUSES = ("Not Sent", "Pending Verification", "Sent", "Delivered", "Failed")
LEAD_IMPORT_STATUSES = ("Uploaded", "Validated", "Imported", "Cancelled")
LEAD_IMPORT_ROW_RESULTS = ("Ready", "Duplicate Review", "Invalid", "Imported")
# demos
DEMO_STATUSES = ("Scheduled", "Confirmed", "Attended", "No Show", "Rescheduled", "Cancelled")
DEMO_MODES = ("In-person", "Online")
DEMO_TYPES = ("Standard", "Practical")
DEMO_REMINDER_TYPES = ("Booking confirmation", "24h student reminder", "1h student + trainer reminder")
DEMO_REMINDER_STATES = ("Pending", "Sent", "Failed", "Skipped", "Superseded", "Cleared", "Not needed")
# commercials
FEE_DISCUSSION_MILESTONES = ("In Discussion", "Approved", "Fee Shared", "Invoice Issued", "Converted", "Expired", "Cancelled")
FEE_VERSION_STATUSES = ("Discussion Saved", "Counteroffered", "Pending Approval", "Approved", "Rejected", "Superseded", "Expired")
SCR_STATUSES = ("Pending", "Approved", "Counteroffered", "Rejected", "Withdrawn", "Expired")
DELIVERY_MODES = ("Classroom", "Online", "Hybrid")
SEAT_TYPES = ("Confirmed Seat", "Future Plan")
INVOICE_STATUSES = ("Issued", "Superseded", "Cancelled")
# money
PAYMENT_ENTRY_TYPES = ("Payment", "Reversal")
PAYMENT_VERIFICATIONS = ("Pending Verification", "Verified", "Failed")
CORRECTION_REQUEST_STATUSES = ("Pending Approval", "Approved", "Rejected")
PROMISE_STATUSES = ("Pending", "Kept", "Broken", "Cancelled")
REFUND_CASE_STATUSES = ("Registered", "Under Assessment", "Decided", "Completed", "Withdrawn")
REFUND_DECISIONS = ("Pending", "Refund Approved", "Waiver Approved", "Rejected")
REFUND_EVIDENCE_STATUSES = ("Evidence Pending", "Evidence Complete")
PAYOUT_STATUSES = ("Not Started", "Approved", "Processing", "Completed", "Failed")
# admissions & academics
ENROLMENT_STATUSES = ("Awaiting Batch Allocation", "Scheduled", "In Progress", "Deferred", "Paused", "Completed", "Cancelled")
CURRICULUM_STATUSES = ("Mapping Pending", "Mapped")
HANDOVER_STATUSES = ("Pending", "Completed")
LMS_STATUSES = ("Not Created", "Invited", "Active", "Inactive", "Completed")
FEE_CHANGE_STATUSES = ("Pending", "Approved", "Rejected", "Applied")
BATCH_STATUSES = ("Planned", "Open", "In Progress", "Completed", "Cancelled")
ALLOCATION_STATUSES = ("Active", "Moved", "Withdrawn", "Completed")
CURRICULUM_VERSION_STATUSES = ("Draft", "Published", "Retired")
DOCUMENT_STATUSES = ("Review Required", "Verified", "Rejected")
CERTIFICATE_STATUSES = ("Eligibility Pending", "Eligible", "Not Eligible", "Issued", "Revoked")
SUPPORT_CASE_STATUSES = ("Open", "In Progress", "Waiting on Student", "Resolved", "Closed")
# operations
COMM_DELIVERY_STATUSES = ("Received", "Sent", "Delivered", "Read", "Failed", "Missed")
COMM_MATCH_STATUSES = ("Matched", "Match Review", "Unmatched")
INTEGRATION_MODES = ("Manual", "API")
INTEGRATION_STATES = ("Planned", "Manual", "Configured", "Live", "Disabled")
VERIFICATION_STATES = ("Pending Verification", "Verified", "Failed")
INCIDENT_SEVERITIES = ("Not Set", "Low", "Medium", "High", "Critical")
INCIDENT_STATUSES = ("Open", "Investigating", "Resolved", "Closed")
DELETION_REQUEST_STATUSES = ("Pending", "Approved", "Rejected", "Executed")
# placement
EMPLOYMENT_TYPES = ("Full-time", "Part-time", "Internship", "Contract")
WORK_MODES = ("On-site", "Hybrid", "Remote")
JOB_STATUSES = ("Review Required", "Open", "On Hold", "Closed", "Filled")
PLACEMENT_READINESS = ("Not Yet Assessed", "In Preparation", "Ready", "Not Seeking")
CV_REVIEW_STATUSES = ("No CV", "Review Pending", "Approved", "Changes Requested")
CONSENT_STATUSES = ("Not Recorded", "Explicit Consent", "Withdrawn")
EVIDENCE_STATUSES = ("Student Reported", "Verification Pending", "Verified")
APPLICATION_STAGES = ("Applied", "Shortlisted", "Interview Scheduled", "Interview Attended", "Selected", "Offer Received",
                      "Offer Accepted", "Joined", "Rejected", "Withdrawn", "Offer Declined")
APPLICATION_EVENT_TYPES = ("Stage Change", "Interview Scheduled", "Interview No-show", "Note", "Evidence Added")
# management
TARGET_STATUSES = ("Draft", "Approved", "Superseded")
REPORT_FREQUENCIES = ("Daily", "Weekly", "Monthly")
REPORT_FORMATS = ("Excel", "CSV", "PDF")
REPORT_COMPLETENESS = ("Complete", "Partial")
# AI
AI_INSIGHT_TYPES = ("Before-Call Brief", "Priority Explanation", "Next Best Action", "Suggested Message", "Management Brief",
                    "Lead Insight")
AI_FEEDBACK_RATINGS = ("Helpful", "Incorrect", "Not Useful", "Missing Context")

CourseStatus = _pg_enum("course_status", COURSE_STATUSES)
OfferStatus = _pg_enum("offer_status", OFFER_STATUSES)
OfferBenefitType = _pg_enum("offer_benefit_type", OFFER_BENEFIT_TYPES)
LeadStage = _pg_enum("lead_stage", LEAD_STAGES)
IntakeStatus = _pg_enum("lead_intake_status", INTAKE_STATUSES)
LeadPriority = _pg_enum("lead_priority", LEAD_PRIORITIES)
ActivityType = _pg_enum("activity_type", ACTIVITY_TYPES)
ActivityDirection = _pg_enum("activity_direction", ACTIVITY_DIRECTIONS)
AppLanguage = _pg_enum("app_language", LANGUAGES)
TaskStatus = _pg_enum("task_status", TASK_STATUSES)
TaskSource = _pg_enum("task_source", TASK_SOURCES)
NotificationCategory = _pg_enum("notification_category", NOTIFICATION_CATEGORIES)
ExternalDeliveryStatus = _pg_enum("external_delivery_status", EXTERNAL_DELIVERY_STATUSES)
LeadImportStatus = _pg_enum("lead_import_status", LEAD_IMPORT_STATUSES)
LeadImportRowResult = _pg_enum("lead_import_row_result", LEAD_IMPORT_ROW_RESULTS)
DemoStatus = _pg_enum("demo_status", DEMO_STATUSES)
DemoMode = _pg_enum("demo_mode", DEMO_MODES)
DemoType = _pg_enum("demo_type", DEMO_TYPES)
DemoReminderType = _pg_enum("demo_reminder_type", DEMO_REMINDER_TYPES)
DemoReminderState = _pg_enum("demo_reminder_state", DEMO_REMINDER_STATES)
FeeDiscussionMilestone = _pg_enum("fee_discussion_milestone", FEE_DISCUSSION_MILESTONES)
FeeVersionStatus = _pg_enum("fee_version_status", FEE_VERSION_STATUSES)
ScrStatus = _pg_enum("scr_status", SCR_STATUSES)
DeliveryMode = _pg_enum("delivery_mode", DELIVERY_MODES)
SeatType = _pg_enum("seat_type", SEAT_TYPES)
InvoiceStatus = _pg_enum("invoice_status", INVOICE_STATUSES)
PaymentEntryType = _pg_enum("payment_entry_type", PAYMENT_ENTRY_TYPES)
PaymentVerification = _pg_enum("payment_verification", PAYMENT_VERIFICATIONS)
CorrectionRequestStatus = _pg_enum("correction_request_status", CORRECTION_REQUEST_STATUSES)
PromiseStatus = _pg_enum("promise_status", PROMISE_STATUSES)
RefundCaseStatus = _pg_enum("refund_case_status", REFUND_CASE_STATUSES)
RefundDecision = _pg_enum("refund_decision", REFUND_DECISIONS)
RefundEvidenceStatus = _pg_enum("refund_evidence_status", REFUND_EVIDENCE_STATUSES)
PayoutStatus = _pg_enum("payout_status", PAYOUT_STATUSES)
EnrolmentStatus = _pg_enum("enrolment_status", ENROLMENT_STATUSES)
CurriculumStatus = _pg_enum("curriculum_status", CURRICULUM_STATUSES)
HandoverStatus = _pg_enum("handover_status", HANDOVER_STATUSES)
LmsStatus = _pg_enum("lms_status", LMS_STATUSES)
FeeChangeStatus = _pg_enum("fee_change_status", FEE_CHANGE_STATUSES)
BatchStatus = _pg_enum("batch_status", BATCH_STATUSES)
AllocationStatus = _pg_enum("allocation_status", ALLOCATION_STATUSES)
CurriculumVersionStatus = _pg_enum("curriculum_version_status", CURRICULUM_VERSION_STATUSES)
DocumentStatus = _pg_enum("document_status", DOCUMENT_STATUSES)
CertificateStatus = _pg_enum("certificate_status", CERTIFICATE_STATUSES)
SupportCaseStatus = _pg_enum("support_case_status", SUPPORT_CASE_STATUSES)
CommDeliveryStatus = _pg_enum("comm_delivery_status", COMM_DELIVERY_STATUSES)
CommMatchStatus = _pg_enum("comm_match_status", COMM_MATCH_STATUSES)
IntegrationMode = _pg_enum("integration_mode", INTEGRATION_MODES)
IntegrationState = _pg_enum("integration_state", INTEGRATION_STATES)
VerificationState = _pg_enum("verification_state", VERIFICATION_STATES)
IncidentSeverity = _pg_enum("incident_severity", INCIDENT_SEVERITIES)
IncidentStatus = _pg_enum("incident_status", INCIDENT_STATUSES)
DeletionRequestStatus = _pg_enum("deletion_request_status", DELETION_REQUEST_STATUSES)
EmploymentType = _pg_enum("employment_type", EMPLOYMENT_TYPES)
WorkMode = _pg_enum("work_mode", WORK_MODES)
JobStatus = _pg_enum("job_status", JOB_STATUSES)
PlacementReadiness = _pg_enum("placement_readiness", PLACEMENT_READINESS)
CvReviewStatus = _pg_enum("cv_review_status", CV_REVIEW_STATUSES)
ConsentStatus = _pg_enum("consent_status", CONSENT_STATUSES)
EvidenceStatus = _pg_enum("evidence_status", EVIDENCE_STATUSES)
ApplicationStage = _pg_enum("application_stage", APPLICATION_STAGES)
ApplicationEventType = _pg_enum("application_event_type", APPLICATION_EVENT_TYPES)
TargetStatus = _pg_enum("target_status", TARGET_STATUSES)
ReportFrequency = _pg_enum("report_frequency", REPORT_FREQUENCIES)
ReportFormat = _pg_enum("report_format", REPORT_FORMATS)
ReportCompleteness = _pg_enum("report_completeness", REPORT_COMPLETENESS)
AiInsightType = _pg_enum("ai_insight_type", AI_INSIGHT_TYPES)
AiFeedbackRating = _pg_enum("ai_feedback_rating", AI_FEEDBACK_RATINGS)

# Stages after which a lead is no longer "open"
CLOSED_STAGES = ("Admitted", "Lost - closed")
# Stages a demo booking / outcome never moves a lead out of (prototype protectedStages)
PROTECTED_STAGES = ("Payment Pending Verification", "Admitted", "Lost - closed")
